import asyncio
import inspect
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

from ai_agents_glossary.agent import root_agent

APP_NAME = "ai_agents_glossary"
USER_ID = "local_user"
SESSION_ID = "glossary_pipeline_session"

OUTPUT_DIR = Path("outputs")
OUTPUT_FILE = OUTPUT_DIR / "ai_agents_glossary_guide.md"

USER_PROMPT = """
Create the AI Agents Glossary and Reference Guide using the full adversarial writer-reviewer pipeline.

Requirements:
- This is an educational writing task only.
- Do not call tools, functions, APIs, browsers, or external services. Mention tools only as prose examples.
- Produce the final polished guide only.
- Include the long-form AI agent definition.
- Include the complete 50-term glossary.
- Include the adversarial review summary.
- Include the final self-critique.
- Do not include intermediate drafts.
- Do not include hidden reasoning.
- Do not include raw reviewer scratch notes.
"""


async def maybe_await(value):
    """Support ADK methods whether they are sync or async in this installed version."""
    if inspect.isawaitable(value):
        return await value
    return value


def extract_text_from_content(content) -> str:
    """Extract readable text from a google.genai Content object."""
    if content is None or not getattr(content, "parts", None):
        return ""

    chunks = []
    for part in content.parts:
        text = getattr(part, "text", None)
        if text:
            chunks.append(text)

    return "\n".join(chunks).strip()


def clean_final_guide(text: str) -> str:
    """
    Keep only the final guide if the model accidentally includes preamble/debug text.
    """
    if not text:
        return text

    marker = "# AI Agents Glossary and Reference Guide"
    index = text.find(marker)

    if index != -1:
        text = text[index:]

    return text.strip() + "\n"


async def main() -> None:
    print("Starting ADK glossary pipeline...")
    print(f"Root agent: {root_agent.name}")
    print(f"Output file: {OUTPUT_FILE}")
    print()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    session_service = InMemorySessionService()

    await maybe_await(
        session_service.create_session(
            app_name=APP_NAME,
            user_id=USER_ID,
            session_id=SESSION_ID,
        )
    )

    runner = Runner(
        agent=root_agent,
        app_name=APP_NAME,
        session_service=session_service,
    )

    message = types.Content(
        role="user",
        parts=[types.Part(text=USER_PROMPT)],
    )

    final_response_text = ""

    print("Running pipeline. This may take several minutes...")
    print()

    async for event in runner.run_async(
        user_id=USER_ID,
        session_id=SESSION_ID,
        new_message=message,
    ):
        author = getattr(event, "author", "unknown")

        if author:
            print(f"Stage event from: {author}")

        if event.is_final_response():
            final_response_text = extract_text_from_content(event.content)

    print()
    print("Pipeline finished. Extracting final guide from session state...")

    session = await maybe_await(
        session_service.get_session(
            app_name=APP_NAME,
            user_id=USER_ID,
            session_id=SESSION_ID,
        )
    )

    final_guide = ""

    if session and getattr(session, "state", None):
        final_guide = session.state.get("final_guide", "")

    if not final_guide:
        print("WARNING: Could not find final_guide in session state.")
        print("Falling back to final response text.")
        final_guide = final_response_text

    final_guide = clean_final_guide(final_guide)

    if not final_guide:
        raise RuntimeError("Pipeline finished, but no final guide text was produced.")

    header = f"<!-- Generated by AI Agents Glossary ADK pipeline on {datetime.now().isoformat(timespec='seconds')} -->\n\n"
    OUTPUT_FILE.write_text(header + final_guide, encoding="utf-8")

    print(f"Saved final guide to: {OUTPUT_FILE}")
    print()
    print("Preview:")
    print("-" * 80)
    print(final_guide[:1500])
    print("-" * 80)
    print()
    print("SUCCESS: Phase 3 pipeline run completed.")


if __name__ == "__main__":
    asyncio.run(main())
